services:
  db:
    image: postgres:14
    container_name: timeblocker_db
    environment:
      POSTGRES_DB: timeblocker
      POSTGRES_USER: timeblocker
      POSTGRES_PASSWORD: timeblocker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
