server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/timeblocker
    username: timeblocker
    password: timeblocker

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
